### ISSUE TITLE
Doesn't work with Vite 6

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-node#24]
There seem to be a regression with `vike-node` on Vite's side:

```
error when starting dev server:
Error: No known conditions for "./client" specifier in "telefunc" package
    at e (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15108:25)
    at n (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15108:646)
    at o (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15108:1297)
    at resolveExportsOrImports (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16306:18)
    at resolveDeepImport (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16319:25)
    at tryNodeResolve (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16149:18)
    at ResolveIdContext.resolveId (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15934:19)
    at EnvironmentPluginContainer.resolveId (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:46930:17)
    at resolve (file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:47447:12)
    at file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:47463:22
    at file:///home/rom/code/telefunc/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.0_terser@5.10.0/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:53253:16
 ELIFECYCLE  Command failed with exit code 1.
```

Reproduction: https://github.com/brillout/telefunc/tree/brillout/reproduction-vike-note-vite-6-bug

**Comment by brillout** [comment]
Closing in favor of https://github.com/vitejs/vite/issues/18864.

**Comment by jasonhilldm** [comment]
Tested with 0.2.2 and can confirm that all is working OK now with vite 6.0.2. Thanks for your help.
