### ISSUE TITLE
How to keep backend server alive while error occurs for better DX

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-node#5]
Hi,
First of all, this is not bug of vike-node, but I think some feature idea to improve for better DX.

On example code server/index.js, I add / for triggering error

```
import express from 'express'
import vike from 'vike-node/connect'

startServer()
/ // for triggering error

function startServer() {
  const app = express()
  app.use(vike())
  const port = process.env.PORT || 3000
  app.listen(port, () => console.log(`Server running at http://localhost:${port}`))
}
```

And it cause error and app exited with code 1

```
ReferenceError: startServer is not defined
    at /Users/forte/Downloads/express-react/server/index.js:4:1
    at instantiateModule (file:///Users/forte/Downloads/express-react/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)
ReferenceError: startServer is not defined
    at /Users/forte/Downloads/express-react/server/index.js:4:1
    at instantiateModule (file:///Users/forte/Downloads/express-react/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)
error: script "dev" exited with code 1
```
I have tried to use pm2 but still not get better DX

Any idea for better DX ?

**Comment by nitedani** [comment]
Yes, I think I can catch these errors and make it log something like: `Server crash, update a server source file or type r + enter to restart the server`.

**Comment by fortezhuo** [comment]
After install latest package. I got warning message in my app (fastify)

```
[2024-08-08 15:52:09] WARN: response will send, but you shouldn't use res.writeHead in stream mode
    reqId: "req-5"
[2024-08-08 15:52:10] WARN: response will send, but you shouldn't use res.writeHead in stream mode
    reqId: "req-5t"
^C
```
