### ISSUE TITLE
WARN: response will send, but you shouldn't use res.writeHead in stream mode [Fastify]

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-node#6]
After install latest package. I got warning message in my app (fastify)

```
[2024-08-08 15:52:09] WARN: response will send, but you shouldn't use res.writeHead in stream mode
    reqId: "req-5"
[2024-08-08 15:52:10] WARN: response will send, but you shouldn't use res.writeHead in stream mode
    reqId: "req-5t"
^C
```

and sometimes got this error

```
[2024-08-08 15:51:46] WARN: Reply was already sent, did you forget to "return reply" in "/__vite_hmr" (GET)?
    reqId: "req-1"
    err: {
      "type": "FastifyError",
      "message": "Reply was already sent, did you forget to \"return reply\" in \"/__vite_hmr\" (GET)?",
      "stack":
          FastifyError: Reply was already sent, did you forget to "return reply" in "/__vite_hmr" (GET)?
              at _Reply.Reply.send (/Users/forte/Workspace/HCML/vera/node_modules/fastify/lib/reply.js:151:26)
              at file:///Users/forte/Workspace/HCML/vera/node_modules/vike-node/dist/runtime/frameworks/fastify.js:38:23
              at PassThrough.handleReadable (file:///Users/forte/Workspace/HCML/vera/node_modules/vike-node/dist/runtime/adapters/createServerResponse.js:22:13)
              at Object.onceWrapper (node:events:632:28)
              at PassThrough.emit (node:events:530:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at processTicksAndRejections (node:internal/process/task_queues:82:21)
      "code": "FST_ERR_REP_ALREADY_SENT",
      "name": "FastifyError",
      "statusCode": 500
    }
```

**Comment by nitedani** [comment]
Thank you. Should be fixed in 0.1.15
